name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        cabal-version: '3.6.2'
    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-install --only-dependencies
    - name: Build
      run: |
        cabal new-configure --enable-tests
        cabal new-build
    - name: Run tests
      run: cabal new-test
    - name: Site build
      run: cabal new-run site -- build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy
      shell: bash
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        ./scripts/deploy
