name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7'
        cabal-version: '3.6.2'
    - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - uses: haskell-actions/run-fourmolu@v6
      with:
        pattern: |
          src/**/*.hs
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-install --only-dependencies
    - name: Add cabal install dir to path
      run: |
        echo "$HOME/.cabal/bin" >> $GITHUB_PATH
    - name: Build
      run: |
        cabal new-configure --enable-tests
        cabal new-build
    - name: Run tests
      run: make test
    - name: Run site build
      run: |
        cabal new-run site -- build
