name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      env:
        BEST_QB: ${{ secrets.BEST_QB_EVER }}
      run: |
        echo "the best quarterback evar is"
        echo "$BEST_QB"
        echo "$BEST_QB" | wc -c
